version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: